
-- ==========================================================
-- ATUALIZAÇÃO - PAINEL DO PROPRIETÁRIO PRO
-- Rode este arquivo UMA VEZ no Supabase > SQL Editor
-- Pode ser executado por cima da versão anterior.
-- ==========================================================

-- 1) CONFIGURAÇÕES DA BARBEARIA
create table if not exists public.business_settings (
  id integer primary key default 1 check (id = 1),
  shop_name text not null default 'Bruno Barbearia',
  phone text not null default '(00) 99999-9999',
  whatsapp text not null default '(00) 99999-9999',
  address text not null default 'Rua da Barbearia, 100 • Centro',
  opening_hours text not null default 'Seg–Sáb • 09:00 às 20:00',
  instagram text,
  updated_at timestamptz not null default now()
);

insert into public.business_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.business_settings enable row level security;

drop policy if exists "business_settings_public_read" on public.business_settings;
create policy "business_settings_public_read"
on public.business_settings
for select
to anon, authenticated
using (true);

drop policy if exists "business_settings_owner_update" on public.business_settings;
create policy "business_settings_owner_update"
on public.business_settings
for update
to authenticated
using (public.is_owner())
with check (public.is_owner());

revoke all on public.business_settings from anon, authenticated;
grant select on public.business_settings to anon, authenticated;
grant update (shop_name, phone, whatsapp, address, opening_hours, instagram, updated_at)
on public.business_settings to authenticated;

-- 2) LOGS / AUDITORIA
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_idx
on public.activity_logs(created_at desc);

create index if not exists activity_logs_entity_idx
on public.activity_logs(entity_type, entity_id);

alter table public.activity_logs enable row level security;

drop policy if exists "logs_owner_read" on public.activity_logs;
create policy "logs_owner_read"
on public.activity_logs
for select
to authenticated
using (public.is_owner());

revoke all on public.activity_logs from anon, authenticated;
grant select on public.activity_logs to authenticated;

-- Função interna para gravar log.
create or replace function public.write_activity_log(
  p_actor_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_description text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_role text;
begin
  if p_actor_id is not null then
    select name, role into v_name, v_role
    from public.profiles
    where id = p_actor_id;
  end if;

  insert into public.activity_logs (
    actor_id, actor_name, actor_role, action,
    entity_type, entity_id, description, metadata
  )
  values (
    p_actor_id, v_name, v_role, p_action,
    p_entity_type, p_entity_id, p_description, coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.write_activity_log(uuid,text,text,text,text,jsonb) from public, anon, authenticated;

-- 3) TRIGGER: LOG DE NOVOS AGENDAMENTOS
create or replace function public.log_appointment_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_service text;
begin
  select name into v_service from public.services where id = new.service_id;

  perform public.write_activity_log(
    new.client_id,
    'appointment_created',
    'appointment',
    new.id::text,
    'Novo agendamento criado para ' ||
      to_char(new.appointment_date, 'DD/MM/YYYY') || ' às ' ||
      to_char(new.appointment_time, 'HH24:MI') ||
      coalesce(' • ' || v_service, ''),
    jsonb_build_object(
      'date', new.appointment_date,
      'time', new.appointment_time,
      'service_id', new.service_id,
      'status', new.status
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_log_appointment_insert on public.appointments;
create trigger trg_log_appointment_insert
after insert on public.appointments
for each row execute function public.log_appointment_insert();

-- 4) LOG AO CANCELAR PELO CLIENTE
create or replace function public.cancel_my_appointment(p_appointment_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date date;
  v_time time;
begin
  update public.appointments
     set status = 'cancelled'
   where id = p_appointment_id
     and client_id = auth.uid()
     and status = 'confirmed'
  returning appointment_date, appointment_time into v_date, v_time;

  if not found then
    raise exception 'Agendamento não encontrado ou não pode ser cancelado.';
  end if;

  perform public.write_activity_log(
    auth.uid(),
    'appointment_cancelled',
    'appointment',
    p_appointment_id::text,
    'Cliente cancelou o agendamento de ' ||
      to_char(v_date, 'DD/MM/YYYY') || ' às ' ||
      to_char(v_time, 'HH24:MI'),
    jsonb_build_object('status', 'cancelled')
  );
end;
$$;

revoke all on function public.cancel_my_appointment(uuid) from public;
grant execute on function public.cancel_my_appointment(uuid) to authenticated;

-- 5) LOG AO PROPRIETÁRIO ALTERAR STATUS
create or replace function public.owner_set_appointment_status(
  p_appointment_id uuid,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_status text;
  v_date date;
  v_time time;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  if p_status not in ('confirmed','completed','cancelled','no_show') then
    raise exception 'Status inválido.';
  end if;

  select status, appointment_date, appointment_time
    into v_old_status, v_date, v_time
  from public.appointments
  where id = p_appointment_id;

  if not found then
    raise exception 'Agendamento não encontrado.';
  end if;

  update public.appointments
     set status = p_status
   where id = p_appointment_id;

  perform public.write_activity_log(
    auth.uid(),
    'appointment_status_changed',
    'appointment',
    p_appointment_id::text,
    'Status do agendamento alterado de ' || v_old_status ||
      ' para ' || p_status || ' • ' ||
      to_char(v_date, 'DD/MM/YYYY') || ' ' ||
      to_char(v_time, 'HH24:MI'),
    jsonb_build_object(
      'old_status', v_old_status,
      'new_status', p_status
    )
  );
end;
$$;

revoke all on function public.owner_set_appointment_status(uuid,text) from public;
grant execute on function public.owner_set_appointment_status(uuid,text) to authenticated;

-- 6) LOG DE ALTERAÇÃO DE SERVIÇOS
create or replace function public.log_service_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.write_activity_log(
      auth.uid(),
      'service_created',
      'service',
      new.id::text,
      'Serviço criado: ' || new.name || ' • R$ ' || new.price::text,
      jsonb_build_object('name',new.name,'price',new.price,'duration',new.duration_minutes)
    );
    return new;
  elsif tg_op = 'UPDATE' then
    perform public.write_activity_log(
      auth.uid(),
      'service_updated',
      'service',
      new.id::text,
      'Serviço alterado: ' || new.name ||
        ' • preço R$ ' || old.price::text || ' → R$ ' || new.price::text,
      jsonb_build_object(
        'old_price',old.price,
        'new_price',new.price,
        'old_active',old.active,
        'new_active',new.active
      )
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.write_activity_log(
      auth.uid(),
      'service_deleted',
      'service',
      old.id::text,
      'Serviço removido: ' || old.name,
      jsonb_build_object('name',old.name)
    );
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_log_service_change on public.services;
create trigger trg_log_service_change
after insert or update or delete on public.services
for each row execute function public.log_service_change();

-- 7) LOG DAS CONFIGURAÇÕES DA BARBEARIA
create or replace function public.log_business_settings_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();

  perform public.write_activity_log(
    auth.uid(),
    'business_settings_updated',
    'business_settings',
    new.id::text,
    'Dados da barbearia foram atualizados.',
    jsonb_build_object(
      'phone',new.phone,
      'whatsapp',new.whatsapp,
      'address',new.address,
      'opening_hours',new.opening_hours
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_business_settings_update on public.business_settings;
create trigger trg_business_settings_update
before update on public.business_settings
for each row execute function public.log_business_settings_update();

-- 8) RPC DE ESTATÍSTICAS PARA O PROPRIETÁRIO
create or replace function public.owner_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  select jsonb_build_object(
    'appointments_today',
      (select count(*) from public.appointments
       where appointment_date = current_date and status <> 'cancelled'),
    'future_appointments',
      (select count(*) from public.appointments
       where appointment_date >= current_date and status = 'confirmed'),
    'total_clients',
      (select count(*) from public.profiles where role = 'client'),
    'completed_revenue',
      coalesce((select sum(s.price)
       from public.appointments a
       join public.services s on s.id = a.service_id
       where a.status = 'completed'),0)
  ) into result;

  return result;
end;
$$;

revoke all on function public.owner_dashboard_stats() from public;
grant execute on function public.owner_dashboard_stats() to authenticated;
