-- ==========================================================
-- BRUNO BARBEARIA - ATUALIZAÇÃO COMPLETA
-- Execute este arquivo no Supabase > SQL Editor > Run.
-- Foi preparado para banco já existente.
-- ==========================================================


-- ==========================================================
-- ATUALIZAÇÃO - PAINEL DO PROPRIETÁRIO PRO
-- Rode este arquivo UMA VEZ no Supabase > SQL Editor
-- Pode ser executado por cima da versão anterior.
-- ==========================================================

-- 1) CONFIGURAÇÕES DA BARBEARIA
create table if not exists public.business_settings (
  id integer primary key default 1 check (id = 1),
  shop_name text not null default 'Bruno Barbearia',
  phone text not null default '(00) 99999-9999',
  whatsapp text not null default '(00) 99999-9999',
  address text not null default 'Rua da Barbearia, 100 • Centro',
  opening_hours text not null default 'Seg–Sáb • 09:00 às 20:00',
  instagram text,
  updated_at timestamptz not null default now()
);

insert into public.business_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.business_settings enable row level security;

drop policy if exists "business_settings_public_read" on public.business_settings;
create policy "business_settings_public_read"
on public.business_settings
for select
to anon, authenticated
using (true);

drop policy if exists "business_settings_owner_update" on public.business_settings;
create policy "business_settings_owner_update"
on public.business_settings
for update
to authenticated
using (public.is_owner())
with check (public.is_owner());

revoke all on public.business_settings from anon, authenticated;
grant select on public.business_settings to anon, authenticated;
grant update (shop_name, phone, whatsapp, address, opening_hours, instagram, updated_at)
on public.business_settings to authenticated;

-- 2) LOGS / AUDITORIA
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_idx
on public.activity_logs(created_at desc);

create index if not exists activity_logs_entity_idx
on public.activity_logs(entity_type, entity_id);

alter table public.activity_logs enable row level security;

drop policy if exists "logs_owner_read" on public.activity_logs;
create policy "logs_owner_read"
on public.activity_logs
for select
to authenticated
using (public.is_owner());

revoke all on public.activity_logs from anon, authenticated;
grant select on public.activity_logs to authenticated;

-- Função interna para gravar log.
create or replace function public.write_activity_log(
  p_actor_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_description text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_role text;
begin
  if p_actor_id is not null then
    select name, role into v_name, v_role
    from public.profiles
    where id = p_actor_id;
  end if;

  insert into public.activity_logs (
    actor_id, actor_name, actor_role, action,
    entity_type, entity_id, description, metadata
  )
  values (
    p_actor_id, v_name, v_role, p_action,
    p_entity_type, p_entity_id, p_description, coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.write_activity_log(uuid,text,text,text,text,jsonb) from public, anon, authenticated;

-- 3) TRIGGER: LOG DE NOVOS AGENDAMENTOS
create or replace function public.log_appointment_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_service text;
begin
  select name into v_service from public.services where id = new.service_id;

  perform public.write_activity_log(
    new.client_id,
    'appointment_created',
    'appointment',
    new.id::text,
    'Novo agendamento criado para ' ||
      to_char(new.appointment_date, 'DD/MM/YYYY') || ' às ' ||
      to_char(new.appointment_time, 'HH24:MI') ||
      coalesce(' • ' || v_service, ''),
    jsonb_build_object(
      'date', new.appointment_date,
      'time', new.appointment_time,
      'service_id', new.service_id,
      'status', new.status
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_log_appointment_insert on public.appointments;
create trigger trg_log_appointment_insert
after insert on public.appointments
for each row execute function public.log_appointment_insert();

-- 4) LOG AO CANCELAR PELO CLIENTE
create or replace function public.cancel_my_appointment(p_appointment_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date date;
  v_time time;
begin
  update public.appointments
     set status = 'cancelled'
   where id = p_appointment_id
     and client_id = auth.uid()
     and status = 'confirmed'
  returning appointment_date, appointment_time into v_date, v_time;

  if not found then
    raise exception 'Agendamento não encontrado ou não pode ser cancelado.';
  end if;

  perform public.write_activity_log(
    auth.uid(),
    'appointment_cancelled',
    'appointment',
    p_appointment_id::text,
    'Cliente cancelou o agendamento de ' ||
      to_char(v_date, 'DD/MM/YYYY') || ' às ' ||
      to_char(v_time, 'HH24:MI'),
    jsonb_build_object('status', 'cancelled')
  );
end;
$$;

revoke all on function public.cancel_my_appointment(uuid) from public;
grant execute on function public.cancel_my_appointment(uuid) to authenticated;

-- 5) LOG AO PROPRIETÁRIO ALTERAR STATUS
create or replace function public.owner_set_appointment_status(
  p_appointment_id uuid,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_status text;
  v_date date;
  v_time time;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  if p_status not in ('confirmed','completed','cancelled','no_show') then
    raise exception 'Status inválido.';
  end if;

  select status, appointment_date, appointment_time
    into v_old_status, v_date, v_time
  from public.appointments
  where id = p_appointment_id;

  if not found then
    raise exception 'Agendamento não encontrado.';
  end if;

  update public.appointments
     set status = p_status
   where id = p_appointment_id;

  perform public.write_activity_log(
    auth.uid(),
    'appointment_status_changed',
    'appointment',
    p_appointment_id::text,
    'Status do agendamento alterado de ' || v_old_status ||
      ' para ' || p_status || ' • ' ||
      to_char(v_date, 'DD/MM/YYYY') || ' ' ||
      to_char(v_time, 'HH24:MI'),
    jsonb_build_object(
      'old_status', v_old_status,
      'new_status', p_status
    )
  );
end;
$$;

revoke all on function public.owner_set_appointment_status(uuid,text) from public;
grant execute on function public.owner_set_appointment_status(uuid,text) to authenticated;

-- 6) LOG DE ALTERAÇÃO DE SERVIÇOS
create or replace function public.log_service_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.write_activity_log(
      auth.uid(),
      'service_created',
      'service',
      new.id::text,
      'Serviço criado: ' || new.name || ' • R$ ' || new.price::text,
      jsonb_build_object('name',new.name,'price',new.price,'duration',new.duration_minutes)
    );
    return new;
  elsif tg_op = 'UPDATE' then
    perform public.write_activity_log(
      auth.uid(),
      'service_updated',
      'service',
      new.id::text,
      'Serviço alterado: ' || new.name ||
        ' • preço R$ ' || old.price::text || ' → R$ ' || new.price::text,
      jsonb_build_object(
        'old_price',old.price,
        'new_price',new.price,
        'old_active',old.active,
        'new_active',new.active
      )
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.write_activity_log(
      auth.uid(),
      'service_deleted',
      'service',
      old.id::text,
      'Serviço removido: ' || old.name,
      jsonb_build_object('name',old.name)
    );
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_log_service_change on public.services;
create trigger trg_log_service_change
after insert or update or delete on public.services
for each row execute function public.log_service_change();

-- 7) LOG DAS CONFIGURAÇÕES DA BARBEARIA
create or replace function public.log_business_settings_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();

  perform public.write_activity_log(
    auth.uid(),
    'business_settings_updated',
    'business_settings',
    new.id::text,
    'Dados da barbearia foram atualizados.',
    jsonb_build_object(
      'phone',new.phone,
      'whatsapp',new.whatsapp,
      'address',new.address,
      'opening_hours',new.opening_hours
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_business_settings_update on public.business_settings;
create trigger trg_business_settings_update
before update on public.business_settings
for each row execute function public.log_business_settings_update();

-- 8) RPC DE ESTATÍSTICAS PARA O PROPRIETÁRIO
create or replace function public.owner_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  select jsonb_build_object(
    'appointments_today',
      (select count(*) from public.appointments
       where appointment_date = current_date and status <> 'cancelled'),
    'future_appointments',
      (select count(*) from public.appointments
       where appointment_date >= current_date and status = 'confirmed'),
    'total_clients',
      (select count(*) from public.profiles where role = 'client'),
    'completed_revenue',
      coalesce((select sum(s.price)
       from public.appointments a
       join public.services s on s.id = a.service_id
       where a.status = 'completed'),0)
  ) into result;

  return result;
end;
$$;

revoke all on function public.owner_dashboard_stats() from public;
grant execute on function public.owner_dashboard_stats() to authenticated;


-- ==========================================================
-- BLOQUEIO DE HORÁRIOS
-- ==========================================================
-- BLOQUEIO DE HORÁRIOS PARA CLIENTES FIXOS

create table if not exists public.blocked_slots (
  id uuid primary key default gen_random_uuid(),
  block_date date not null,
  block_time time not null,
  reserved_for text not null,
  client_phone text,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists blocked_slots_unique_slot
on public.blocked_slots (block_date, block_time);

alter table public.blocked_slots enable row level security;

drop policy if exists "blocked_slots_owner_select" on public.blocked_slots;
create policy "blocked_slots_owner_select"
on public.blocked_slots
for select
to authenticated
using (public.is_owner());

drop policy if exists "blocked_slots_owner_insert" on public.blocked_slots;
create policy "blocked_slots_owner_insert"
on public.blocked_slots
for insert
to authenticated
with check (public.is_owner() and created_by = auth.uid());

drop policy if exists "blocked_slots_owner_delete" on public.blocked_slots;
create policy "blocked_slots_owner_delete"
on public.blocked_slots
for delete
to authenticated
using (public.is_owner());

revoke all on public.blocked_slots from anon, authenticated;
grant select, insert, delete on public.blocked_slots to authenticated;

create or replace function public.prevent_block_on_booked_slot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from public.appointments
    where appointment_date = new.block_date
      and appointment_time = new.block_time
      and status in ('confirmed','completed')
  ) then
    raise exception 'Este horário já possui um agendamento.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_block_on_booked_slot on public.blocked_slots;
create trigger trg_prevent_block_on_booked_slot
before insert or update on public.blocked_slots
for each row execute function public.prevent_block_on_booked_slot();

create or replace function public.prevent_booking_on_blocked_slot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'confirmed' and exists (
    select 1 from public.blocked_slots
    where block_date = new.appointment_date
      and block_time = new.appointment_time
  ) then
    raise exception 'Este horário está reservado e não pode ser agendado.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_booking_on_blocked_slot on public.appointments;
create trigger trg_prevent_booking_on_blocked_slot
before insert or update of appointment_date, appointment_time, status
on public.appointments
for each row execute function public.prevent_booking_on_blocked_slot();

create or replace function public.get_booked_times(p_date date)
returns table (appointment_time time)
language sql
stable
security definer
set search_path = public
as $$
  select x.appointment_time
  from (
    select appointment_time
    from public.appointments
    where appointment_date = p_date
      and status in ('confirmed','completed')
    union
    select block_time
    from public.blocked_slots
    where block_date = p_date
  ) x
  order by x.appointment_time;
$$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;


-- ==========================================================
-- BLOQUEIO RECORRENTE
-- ==========================================================
-- ==========================================================
-- BLOQUEIO RECORRENTE DE HORÁRIOS
-- Rode no Supabase > SQL Editor depois do update_blocked_slots.sql
-- ==========================================================

alter table public.blocked_slots
  add column if not exists group_id uuid,
  add column if not exists recurrence_days integer,
  add column if not exists recurrence_weekday integer;

-- Agrupa bloqueios antigos individualmente.
update public.blocked_slots
set group_id = gen_random_uuid()
where group_id is null;

-- Cria uma série: ex. toda terça às 15h por 90 dias.
create or replace function public.owner_create_recurring_block(
  p_start_date date,
  p_weekday integer,
  p_time time,
  p_duration_days integer,
  p_reserved_for text,
  p_client_phone text default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date date;
  v_end_date date;
  v_group_id uuid := gen_random_uuid();
  v_created integer := 0;
  v_skipped integer := 0;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  if p_weekday not between 0 and 6 then
    raise exception 'Dia da semana inválido.';
  end if;

  if p_duration_days not in (30,90,120,365) then
    raise exception 'Duração inválida.';
  end if;

  if p_start_date < current_date then
    raise exception 'A data inicial não pode estar no passado.';
  end if;

  if nullif(trim(p_reserved_for),'') is null then
    raise exception 'Informe o nome do cliente.';
  end if;

  v_end_date := p_start_date + (p_duration_days - 1);

  for v_date in
    select d::date
    from generate_series(
      p_start_date::timestamp,
      v_end_date::timestamp,
      interval '1 day'
    ) d
    where extract(dow from d)::integer = p_weekday
  loop
    -- Se já houver agendamento ou bloqueio nesse horário, ignora essa ocorrência.
    if exists (
      select 1
      from public.appointments a
      where a.appointment_date = v_date
        and a.appointment_time = p_time
        and a.status in ('confirmed','completed')
    ) or exists (
      select 1
      from public.blocked_slots b
      where b.block_date = v_date
        and b.block_time = p_time
    ) then
      v_skipped := v_skipped + 1;
    else
      insert into public.blocked_slots (
        block_date,
        block_time,
        reserved_for,
        client_phone,
        notes,
        created_by,
        group_id,
        recurrence_days,
        recurrence_weekday
      )
      values (
        v_date,
        p_time,
        trim(p_reserved_for),
        p_client_phone,
        p_notes,
        auth.uid(),
        v_group_id,
        p_duration_days,
        p_weekday
      );

      v_created := v_created + 1;
    end if;
  end loop;

  if v_created = 0 then
    raise exception 'Nenhum horário pôde ser bloqueado. Todos os horários da série já estão ocupados.';
  end if;

  return jsonb_build_object(
    'group_id', v_group_id,
    'created', v_created,
    'skipped', v_skipped,
    'start_date', p_start_date,
    'end_date', v_end_date
  );
end;
$$;

revoke all on function public.owner_create_recurring_block(date,integer,time,integer,text,text,text) from public;
grant execute on function public.owner_create_recurring_block(date,integer,time,integer,text,text,text) to authenticated;

-- Libera uma série inteira.
create or replace function public.owner_delete_block_group(p_group_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  delete from public.blocked_slots
  where group_id = p_group_id;

  get diagnostics v_count = row_count;

  return v_count;
end;
$$;

revoke all on function public.owner_delete_block_group(uuid) from public;
grant execute on function public.owner_delete_block_group(uuid) to authenticated;

-- Garante que a disponibilidade dos clientes continue considerando
-- tanto agendamentos quanto bloqueios recorrentes.
create or replace function public.get_booked_times(p_date date)
returns table (appointment_time time)
language sql
stable
security definer
set search_path = public
as $$
  select x.appointment_time
  from (
    select a.appointment_time
    from public.appointments a
    where a.appointment_date = p_date
      and a.status in ('confirmed','completed')

    union

    select b.block_time
    from public.blocked_slots b
    where b.block_date = p_date
  ) x
  order by x.appointment_time;
$$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;


-- ==========================================================
-- CONFERÊNCIA FINAL
-- ==========================================================
select 'profiles' as tabela, count(*) as registros from public.profiles
union all
select 'services', count(*) from public.services
union all
select 'appointments', count(*) from public.appointments
union all
select 'blocked_slots', count(*) from public.blocked_slots
union all
select 'activity_logs', count(*) from public.activity_logs;


-- ==========================================================
-- BRUNO BARBEARIA
-- ATUALIZAÇÃO: TODA SEMANA / SEMANA SIM, SEMANA NÃO
-- Execute no Supabase > SQL Editor > Run
-- ==========================================================

alter table public.blocked_slots
  add column if not exists recurrence_frequency_weeks integer not null default 1;

-- Remove a versão antiga para evitar conflito de assinatura.
drop function if exists public.owner_create_recurring_block(
  date, integer, time, integer, text, text, text
);

drop function if exists public.owner_create_recurring_block(
  date, integer, time, integer, integer, text, text, text
);

create or replace function public.owner_create_recurring_block(
  p_start_date date,
  p_weekday integer,
  p_time time,
  p_duration_days integer,
  p_frequency_weeks integer,
  p_reserved_for text,
  p_client_phone text default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_first_date date;
  v_date date;
  v_end_date date;
  v_group_id uuid := gen_random_uuid();
  v_created integer := 0;
  v_skipped integer := 0;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  if p_weekday not between 0 and 6 then
    raise exception 'Dia da semana inválido.';
  end if;

  if p_duration_days not in (30,90,120,365) then
    raise exception 'Duração inválida.';
  end if;

  if p_frequency_weeks not in (1,2) then
    raise exception 'Frequência inválida.';
  end if;

  if p_start_date < current_date then
    raise exception 'A data inicial não pode estar no passado.';
  end if;

  if nullif(trim(p_reserved_for),'') is null then
    raise exception 'Informe o nome do cliente.';
  end if;

  v_end_date := p_start_date + (p_duration_days - 1);

  -- Primeiro dia escolhido da semana a partir da data inicial.
  v_first_date :=
    p_start_date
    + ((p_weekday - extract(dow from p_start_date)::integer + 7) % 7);

  -- 7 dias = toda semana
  -- 14 dias = semana sim, semana não
  for v_date in
    select d::date
    from generate_series(
      v_first_date::timestamp,
      v_end_date::timestamp,
      make_interval(days => 7 * p_frequency_weeks)
    ) d
  loop

    if exists (
      select 1
      from public.appointments a
      where a.appointment_date = v_date
        and a.appointment_time = p_time
        and a.status in ('confirmed','completed')
    )
    or exists (
      select 1
      from public.blocked_slots b
      where b.block_date = v_date
        and b.block_time = p_time
    ) then
      v_skipped := v_skipped + 1;

    else
      insert into public.blocked_slots (
        block_date,
        block_time,
        reserved_for,
        client_phone,
        notes,
        created_by,
        group_id,
        recurrence_days,
        recurrence_weekday,
        recurrence_frequency_weeks
      )
      values (
        v_date,
        p_time,
        trim(p_reserved_for),
        p_client_phone,
        p_notes,
        auth.uid(),
        v_group_id,
        p_duration_days,
        p_weekday,
        p_frequency_weeks
      );

      v_created := v_created + 1;
    end if;
  end loop;

  if v_created = 0 then
    raise exception 'Nenhum horário pôde ser bloqueado. Os horários da série já estão ocupados.';
  end if;

  return jsonb_build_object(
    'group_id', v_group_id,
    'created', v_created,
    'skipped', v_skipped,
    'frequency_weeks', p_frequency_weeks,
    'start_date', p_start_date,
    'end_date', v_end_date
  );
end;
$$;

revoke all on function public.owner_create_recurring_block(
  date,integer,time,integer,integer,text,text,text
) from public;

grant execute on function public.owner_create_recurring_block(
  date,integer,time,integer,integer,text,text,text
) to authenticated;

-- Disponibilidade continua considerando bloqueios e agendamentos.
create or replace function public.get_booked_times(p_date date)
returns table (appointment_time time)
language sql
stable
security definer
set search_path = public
as $$
  select x.appointment_time
  from (
    select a.appointment_time
    from public.appointments a
    where a.appointment_date = p_date
      and a.status in ('confirmed','completed')

    union

    select b.block_time
    from public.blocked_slots b
    where b.block_date = p_date
  ) x
  order by x.appointment_time;
$$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;


-- ==========================================================
-- BRUNO BARBEARIA - GRADE DE HORÁRIOS 40 EM 40 MINUTOS
-- Segunda a sexta: 08:00 até 19:20
-- Sábado: 08:00 até 16:40
-- Domingo: fechado
-- Execute no Supabase > SQL Editor > Run
-- ==========================================================

create or replace function public.is_valid_barbershop_slot(
  p_date date,
  p_time time
)
returns boolean
language plpgsql
immutable
as $$
declare
  v_dow integer;
  v_minutes integer;
begin
  v_dow := extract(dow from p_date)::integer;

  -- Domingo
  if v_dow = 0 then
    return false;
  end if;

  v_minutes :=
    extract(hour from p_time)::integer * 60
    + extract(minute from p_time)::integer;

  -- Começa às 08:00
  if v_minutes < 480 then
    return false;
  end if;

  -- Somente de 40 em 40 minutos
  if mod(v_minutes - 480, 40) <> 0 then
    return false;
  end if;

  -- Sábado: último horário 16:40
  if v_dow = 6 then
    return v_minutes <= 1000;
  end if;

  -- Segunda a sexta: último horário 19:20
  return v_minutes <= 1160;
end;
$$;

create or replace function public.validate_appointment_slot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_barbershop_slot(
    new.appointment_date,
    new.appointment_time
  ) then
    raise exception 'Horário fora do funcionamento da barbearia.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validate_appointment_slot on public.appointments;
create trigger trg_validate_appointment_slot
before insert or update of appointment_date, appointment_time
on public.appointments
for each row execute function public.validate_appointment_slot();

create or replace function public.validate_blocked_slot_time()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_barbershop_slot(
    new.block_date,
    new.block_time
  ) then
    raise exception 'Horário fora do funcionamento da barbearia.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validate_blocked_slot_time on public.blocked_slots;
create trigger trg_validate_blocked_slot_time
before insert or update of block_date, block_time
on public.blocked_slots
for each row execute function public.validate_blocked_slot_time();

update public.business_settings
set opening_hours = 'Seg–Sex • 08:00 às 19:20 • Sáb • 08:00 às 17:00'
where id = 1;


-- ==========================================================
-- BRUNO BARBEARIA - AGENDAMENTO MANUAL PELO PROPRIETÁRIO
-- Permite marcar para pessoas sem conta, celular ou e-mail.
-- Execute no Supabase > SQL Editor > Run.
-- ==========================================================

-- Cliente cadastrado deixa de ser obrigatório para agendamentos feitos pelo dono.
alter table public.appointments
  alter column client_id drop not null;

alter table public.appointments
  add column if not exists manual_client_name text,
  add column if not exists manual_client_phone text,
  add column if not exists created_by_owner uuid references public.profiles(id) on delete set null;

-- Proteção: um agendamento deve ser de um cliente cadastrado OU possuir nome manual.
alter table public.appointments
  drop constraint if exists appointments_client_identity_check;

alter table public.appointments
  add constraint appointments_client_identity_check
  check (
    client_id is not null
    or nullif(trim(manual_client_name), '') is not null
  );

-- Função segura: somente o proprietário pode criar agendamento manual.
create or replace function public.owner_create_manual_appointment(
  p_client_name text,
  p_client_phone text,
  p_service_id bigint,
  p_date date,
  p_time time,
  p_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_service_name text;
begin
  if not public.is_owner() then
    raise exception 'Acesso negado.';
  end if;

  if nullif(trim(p_client_name), '') is null then
    raise exception 'Informe o nome da pessoa.';
  end if;

  if p_date < current_date then
    raise exception 'A data não pode estar no passado.';
  end if;

  if not exists (
    select 1
    from public.services
    where id = p_service_id
      and active = true
  ) then
    raise exception 'Serviço inválido.';
  end if;

  -- Bloqueios recorrentes e horários já ocupados também são respeitados.
  if exists (
    select 1
    from public.blocked_slots
    where block_date = p_date
      and block_time = p_time
  ) then
    raise exception 'Este horário está bloqueado.';
  end if;

  if exists (
    select 1
    from public.appointments
    where appointment_date = p_date
      and appointment_time = p_time
      and status in ('confirmed','completed')
  ) then
    raise exception 'Este horário já está ocupado.';
  end if;

  insert into public.appointments (
    client_id,
    service_id,
    appointment_date,
    appointment_time,
    status,
    notes,
    manual_client_name,
    manual_client_phone,
    created_by_owner
  )
  values (
    null,
    p_service_id,
    p_date,
    p_time,
    'confirmed',
    p_notes,
    trim(p_client_name),
    nullif(trim(coalesce(p_client_phone, '')), ''),
    auth.uid()
  )
  returning id into v_id;

  select name
  into v_service_name
  from public.services
  where id = p_service_id;

  -- Log adicional específico para identificar que foi o proprietário.
  perform public.write_activity_log(
    auth.uid(),
    'manual_appointment_created',
    'appointment',
    v_id::text,
    'Proprietário marcou horário para ' || trim(p_client_name) ||
      ' • ' || to_char(p_date, 'DD/MM/YYYY') ||
      ' às ' || to_char(p_time, 'HH24:MI') ||
      coalesce(' • ' || v_service_name, ''),
    jsonb_build_object(
      'client_name', trim(p_client_name),
      'client_phone', p_client_phone,
      'date', p_date,
      'time', p_time,
      'service_id', p_service_id
    )
  );

  return v_id;
end;
$$;

revoke all on function public.owner_create_manual_appointment(
  text,text,bigint,date,time,text
) from public;

grant execute on function public.owner_create_manual_appointment(
  text,text,bigint,date,time,text
) to authenticated;

-- A consulta de horários disponíveis já considera todos os registros
-- da tabela appointments, incluindo os agendados manualmente.


-- ==========================================================
-- CORREÇÃO: AGENDAMENTO MANUAL RESPEITAR HORÁRIOS BLOQUEADOS
-- Execute no Supabase > SQL Editor > Run
-- ==========================================================

alter table public.blocked_slots enable row level security;

drop policy if exists "blocked_slots_owner_select" on public.blocked_slots;

create policy "blocked_slots_owner_select"
on public.blocked_slots
for select
to authenticated
using (public.is_owner());

grant select on public.blocked_slots to authenticated;

-- Garante também que a função de disponibilidade considera
-- agendamentos + horários bloqueados.
create or replace function public.get_booked_times(p_date date)
returns table (appointment_time time)
language sql
stable
security definer
set search_path = public
as $$
  select x.appointment_time
  from (
    select a.appointment_time
    from public.appointments a
    where a.appointment_date = p_date
      and a.status in ('confirmed','completed')

    union

    select b.block_time as appointment_time
    from public.blocked_slots b
    where b.block_date = p_date
  ) x
  order by x.appointment_time;
$$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;
